version: "3.8"

services:
  shopping-app:
    image: neharote/task:latest
    container_name: shopping-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/buckets"]
      interval: 30s
      timeout: 5s
      retries: 3